name: logi_neko
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.3
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  http: ^1.2.2
  cached_network_image: ^3.3.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  video_player: ^2.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  auto_route_generator: ^8.0.0
  font_awesome_flutter: 10.9.1
  flutter_lints: ^5.0.0

flutter:

  assets:
  - .env
  - lib/shared/assets/images/
  uses-material-design: true
