name: logi_neko
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  auto_route: ^8.1.3
  http: ^1.1.0

  cached_network_image: ^3.3.0

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  auto_route_generator: ^8.0.0

  flutter_lints: ^5.0.0

flutter:

  assets:
  - lib/shared/assets/images/
  uses-material-design: true


